package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Competition generated by hbm2java
 */
public class Competition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7852464211652832016L;
	private Integer id;
	private int ctId;
	private String workName;
	private int level;
	private int rank;
	private String member1;
	private String member2;
	private String member3;
	private String member4;
	private String member5;
	private String member6;
	private String member7;
	private String member8;
	private String member9;
	private String member10;
	private String teacher;
	private Date winningTime;
	private String period;
	private int term;
	private int isPass;

	public Competition() {
	}

	public Competition(int ctId, String workName, int level, int rank, String member1, String teacher, Date winningTime,
			String period, int term, int isPass) {
		this.ctId = ctId;
		this.workName = workName;
		this.level = level;
		this.rank = rank;
		this.member1 = member1;
		this.teacher = teacher;
		this.winningTime = winningTime;
		this.period = period;
		this.term = term;
		this.isPass = isPass;
	}

	public Competition(int ctId, String workName, int level, int rank, String member1, String member2, String member3,
			String member4, String member5, String member6, String member7, String member8, String member9,
			String member10, String teacher, Date winningTime, String period, int term, int isPass) {
		this.ctId = ctId;
		this.workName = workName;
		this.level = level;
		this.rank = rank;
		this.member1 = member1;
		this.member2 = member2;
		this.member3 = member3;
		this.member4 = member4;
		this.member5 = member5;
		this.member6 = member6;
		this.member7 = member7;
		this.member8 = member8;
		this.member9 = member9;
		this.member10 = member10;
		this.teacher = teacher;
		this.winningTime = winningTime;
		this.period = period;
		this.term = term;
		this.isPass = isPass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCtId() {
		return this.ctId;
	}

	public void setCtId(int ctId) {
		this.ctId = ctId;
	}

	public String getWorkName() {
		return this.workName;
	}

	public void setWorkName(String workName) {
		this.workName = workName;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getMember1() {
		return this.member1;
	}

	public void setMember1(String member1) {
		this.member1 = member1;
	}

	public String getMember2() {
		return this.member2;
	}

	public void setMember2(String member2) {
		this.member2 = member2;
	}

	public String getMember3() {
		return this.member3;
	}

	public void setMember3(String member3) {
		this.member3 = member3;
	}

	public String getMember4() {
		return this.member4;
	}

	public void setMember4(String member4) {
		this.member4 = member4;
	}

	public String getMember5() {
		return this.member5;
	}

	public void setMember5(String member5) {
		this.member5 = member5;
	}

	public String getMember6() {
		return this.member6;
	}

	public void setMember6(String member6) {
		this.member6 = member6;
	}

	public String getMember7() {
		return this.member7;
	}

	public void setMember7(String member7) {
		this.member7 = member7;
	}

	public String getMember8() {
		return this.member8;
	}

	public void setMember8(String member8) {
		this.member8 = member8;
	}

	public String getMember9() {
		return this.member9;
	}

	public void setMember9(String member9) {
		this.member9 = member9;
	}

	public String getMember10() {
		return this.member10;
	}

	public void setMember10(String member10) {
		this.member10 = member10;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public Date getWinningTime() {
		return this.winningTime;
	}

	public void setWinningTime(Date winningTime) {
		this.winningTime = winningTime;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public int getTerm() {
		return this.term;
	}

	public void setTerm(int term) {
		this.term = term;
	}

	public int getIsPass() {
		return this.isPass;
	}

	public void setIsPass(int isPass) {
		this.isPass = isPass;
	}

}
