package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4745710588441204803L;
	private Integer id;
	private String number;
	private String password;
	private Integer userId;
	private Integer role;
	private Integer status;
	private Date createtime;
	private Date loginTime;

	public Login() {
	}

	public Login(String number, String password, int userId, int role, int status, Date createtime) {
		this.number = number;
		this.password = password;
		this.userId = userId;
		this.role = role;
		this.status = status;
		this.createtime = createtime;
	}

	public Login(String number, String password, int userId, int role, int status, Date createtime, Date loginTime) {
		this.number = number;
		this.password = password;
		this.userId = userId;
		this.role = role;
		this.status = status;
		this.createtime = createtime;
		this.loginTime = loginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

}
