package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7054029183928576155L;
	private Integer id;
	private Integer projectId;
	private Integer senderId;
	private Integer receiverId;
	private Integer status;
	private String content;
	private Date createtime;

	public Message() {
	}

	public Message(int projectId, int senderId, int receiverId, int status, String content, Date createtime) {
		this.projectId = projectId;
		this.senderId = senderId;
		this.receiverId = receiverId;
		this.status = status;
		this.content = content;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public Integer getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	public Integer getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(Integer receiverId) {
		this.receiverId = receiverId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
