package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Paper generated by hbm2java
 */
public class Paper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2610629714340480271L;
	private Integer id;
	private String college;
	private String name;
	private String periodical;
	private String number;
	private String level;
	private Date time;
	private String member1;
	private String member2;
	private String member3;
	private String member4;
	private String member5;
	private String member6;
	private String member7;
	private String member8;
	private String member9;
	private String member10;
	private String teacher;
	private String authorName;
	private String authorNumber;
	private String authorTelephone;
	private Integer isPass;

	public Paper() {
	}

	public Paper(String college, String name, String periodical, String number, String level, Date time, String teacher,
			int isPass) {
		this.college = college;
		this.name = name;
		this.periodical = periodical;
		this.number = number;
		this.level = level;
		this.time = time;
		this.teacher = teacher;
		this.isPass = isPass;
	}

	public Paper(String college, String name, String periodical, String number, String level, Date time, String member1,
			String member2, String member3, String member4, String member5, String member6, String member10,
			String teacher, String authorName, String authorNumber, String authorTelephone, int isPass) {
		this.college = college;
		this.name = name;
		this.periodical = periodical;
		this.number = number;
		this.level = level;
		this.time = time;
		this.member1 = member1;
		this.member2 = member2;
		this.member3 = member3;
		this.member4 = member4;
		this.member5 = member5;
		this.member6 = member6;
		this.member10 = member10;
		this.teacher = teacher;
		this.authorName = authorName;
		this.authorNumber = authorNumber;
		this.authorTelephone = authorTelephone;
		this.isPass = isPass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCollege() {
		return this.college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPeriodical() {
		return this.periodical;
	}

	public void setPeriodical(String periodical) {
		this.periodical = periodical;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getMember1() {
		return this.member1;
	}

	public void setMember1(String member1) {
		this.member1 = member1;
	}

	public String getMember2() {
		return this.member2;
	}

	public void setMember2(String member2) {
		this.member2 = member2;
	}

	public String getMember3() {
		return this.member3;
	}

	public void setMember3(String member3) {
		this.member3 = member3;
	}

	public String getMember4() {
		return this.member4;
	}

	public void setMember4(String member4) {
		this.member4 = member4;
	}

	public String getMember5() {
		return this.member5;
	}

	public void setMember5(String member5) {
		this.member5 = member5;
	}

	public String getMember6() {
		return this.member6;
	}

	public void setMember6(String member6) {
		this.member6 = member6;
	}

	public String getMember7() {
		return member7;
	}

	public void setMember7(String member7) {
		this.member7 = member7;
	}

	public String getMember8() {
		return member8;
	}

	public void setMember8(String member8) {
		this.member8 = member8;
	}

	public String getMember9() {
		return member9;
	}

	public void setMember9(String member9) {
		this.member9 = member9;
	}
	public String getMember10() {
		return this.member10;
	}

	public void setMember10(String member10) {
		this.member10 = member10;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public String getAuthorNumber() {
		return this.authorNumber;
	}

	public void setAuthorNumber(String authorNumber) {
		this.authorNumber = authorNumber;
	}

	public String getAuthorTelephone() {
		return this.authorTelephone;
	}

	public void setAuthorTelephone(String authorTelephone) {
		this.authorTelephone = authorTelephone;
	}

	public Integer getIsPass() {
		return this.isPass;
	}

	public void setIsPass(Integer isPass) {
		this.isPass = isPass;
	}

}
