package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

/**
 * StudentTagRelation generated by hbm2java
 */
public class StudentTagRelation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4198908229636086803L;
	private Integer id;
	private Integer loginId;
	private Integer tagId1;
	private Integer tagId2;
	private Integer tagId3;
	private Integer tagId4;
	private Integer tagId5;
	private Integer tagId6;

	public StudentTagRelation() {
	}

	public StudentTagRelation(int loginId) {
		this.loginId = loginId;
	}

	public StudentTagRelation(int loginId, Integer tagId1, Integer tagId2, Integer tagId3, Integer tagId4,
			Integer tagId5, Integer tagId6) {
		this.loginId = loginId;
		this.tagId1 = tagId1;
		this.tagId2 = tagId2;
		this.tagId3 = tagId3;
		this.tagId4 = tagId4;
		this.tagId5 = tagId5;
		this.tagId6 = tagId6;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	public Integer getTagId1() {
		return this.tagId1;
	}

	public void setTagId1(Integer tagId1) {
		this.tagId1 = tagId1;
	}

	public Integer getTagId2() {
		return this.tagId2;
	}

	public void setTagId2(Integer tagId2) {
		this.tagId2 = tagId2;
	}

	public Integer getTagId3() {
		return this.tagId3;
	}

	public void setTagId3(Integer tagId3) {
		this.tagId3 = tagId3;
	}

	public Integer getTagId4() {
		return this.tagId4;
	}

	public void setTagId4(Integer tagId4) {
		this.tagId4 = tagId4;
	}

	public Integer getTagId5() {
		return this.tagId5;
	}

	public void setTagId5(Integer tagId5) {
		this.tagId5 = tagId5;
	}

	public Integer getTagId6() {
		return this.tagId6;
	}

	public void setTagId6(Integer tagId6) {
		this.tagId6 = tagId6;
	}

}
