package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4543237968231858520L;
	private Integer id;
	private String name;
	private Integer num;

	public Tag() {
	}

	public Tag(String name, int num) {
		this.name = name;
		this.num = num;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

}
