package edu.zjut.tempest.entity;
// Generated 2017-3-9 20:00:46 by Hibernate Tools 5.2.0.CR1

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8770063778211892872L;
	private Integer id;
	private String name;
	private Integer sex;
	private String academy;
	private Integer level;
	private String telephone;
	private String cornet;
	private String qq;
	private String email;
	private String description;

	public Teacher() {
	}

	public Teacher(String name, int sex, String academy, int level, String telephone) {
		this.name = name;
		this.sex = sex;
		this.academy = academy;
		this.level = level;
		this.telephone = telephone;
	}

	public Teacher(String name, int sex, String academy, int level, String telephone, String cornet, String qq,
			String email, String description) {
		this.name = name;
		this.sex = sex;
		this.academy = academy;
		this.level = level;
		this.telephone = telephone;
		this.cornet = cornet;
		this.qq = qq;
		this.email = email;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getAcademy() {
		return this.academy;
	}

	public void setAcademy(String academy) {
		this.academy = academy;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getCornet() {
		return this.cornet;
	}

	public void setCornet(String cornet) {
		this.cornet = cornet;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
